---
title: "03_pipes-filters"
author: "Reid Otsuji"
date: "3/4/2018"
output: html_document
---

# Lesson 3:  Pipes and Filters
* Redirect a command’s output to a file.
* Process a file instead of keyboard input using redirection.
* Construct command pipelines with two or more stages.
* Explain what usually happens if a program or pipeline isn’t given any input to process.
* Explain Unix’s “small pieces, loosely joined” philosophy.


Now that we know a few basic commands, let’s take a look at the shell’s most powerful feature: the ease with which it lets us combine existing programs in new ways. 

We’ll start with a directory called molecules that contains six files describing some simple organic molecules. The .pdb extension indicates that these files are in Protein Data Bank format, a simple text format that specifies the type and position of each atom in the molecule.

To get started, 

Make sure you are in the data-shell folder. if not navigate to the folder in the shell.  

You can check by typing:


```bash
pwd
```

    /Users/rotsuji/desktop/sio-swc/data-shell



```bash
ls -F
```

    Desktop/		north-pacific-gyre/	thesis/
    creatures/		notes.txt		writing/
    data/			pizza.cfg
    molecules/		solar.pdf


Change to the molecules directory.


```bash
cd molecules
```

    

Let’s go into that directory with cd and run the command wc *.pdb. 

wc is the “word count” command: it counts the number of lines, words, and characters in files.


```bash
wc *.pdb
```

          20     156    1158 cubane.pdb
          12      84     622 ethane.pdb
           9      57     422 methane.pdb
          30     246    1828 octane.pdb
          21     165    1226 pentane.pdb
          15     111     825 propane.pdb
         107     819    6081 total


The **\* in \*.pdb** matches zero or more characters, so the shell turns*.pdb into a complete list of .pdb files:

now, If we run **wc -l** instead of just **wc**, the output shows only the **number of lines** per file:


```bash
wc -l *.pdb
```

          20 cubane.pdb
          12 ethane.pdb
           9 methane.pdb
          30 octane.pdb
          21 pentane.pdb
          15 propane.pdb
         107 total


Which of these files is shortest? 

methane.pdb

It’s an easy question to answer when there are only six files, but what if there were 6000? 

Our first step toward a solution is to run the command:



```bash
wc -l *.pdb > lengths.txt
```

    

The **greater than symbol, >,** tells the shell to redirect the command’s output to a file instead of printing it to the screen. (This is why there is no screen output: everything that wc would have printed has gone into the file lengths.txt instead.) 

The shell will create the file if it doesn’t exist. If the file exists, it will be silently overwritten, which may lead to data loss and thus requires some caution. 

to confirm the file exists type:


```bash
ls lengths.txt
```

    lengths.txt


We can now send the content of **lengths.txt** to the screen using **cat lengths.txt.** 

**cat stands for “concatenate”:** it prints the contents of files one after another. 

There’s only one file in this case, so cat just shows us what it contains:


```bash
cat lengths.txt
```

          20 cubane.pdb
          12 ethane.pdb
           9 methane.pdb
          30 octane.pdb
          21 pentane.pdb
          15 propane.pdb
         107 total


Now let’s use the **sort** command to sort its contents. 

We will also use the **-n flag** to specify that the **sort is numerical instead of alphabetical.** 

This does not change the file; instead, it sends the sorted result to the screen:



```bash
sort -n lengths.txt
```

           9 methane.pdb
          12 ethane.pdb
          15 propane.pdb
          20 cubane.pdb
          21 pentane.pdb
          30 octane.pdb
         107 total


We can put the sorted list of lines in another temporary file called **sorted-lengths.txt** by putting **> sorted-lengths.txt**  after the command, just as we used **> lengths.txt** to put the output of **wc** into **lengths.txt.**


```bash
sort -n lengths.txt > sorted-lengths.txt
```

    


```bash
ls sorted-lengths.txt
```

    sorted-lengths.txt


Once we’ve done that, we can run another command called **head** to get the first few lines in **sorted-lengths.txt:**


```bash
head -1 sorted-lengths.txt
```

           9 methane.pdb


Using the parameter **-1** with **head** tells it that we only want the first line of the file; **-20** would get the first 20, and so on. 

Since **sorted-lengths.txt** contains the lengths of our files ordered from least to greatest, the output of **head** must be the file with the fewest lines.

	This may be a little confusing to understand what’s going on. 

We can make it easier to understand by running **sort** and **head** together:


```bash
sort -n lengths.txt | head -1
```

           9 methane.pdb


Here we used the vertical bar between the two commands which is called a pipe. It tells the shell that we want to use the output of the command on the left as the input to the command on the right.

Nothing prevents us from chaining pipes consecutively. 

for example send the output of wc directly tosort, and then the resulting output to head. Thus we first use a pipe to send the output of wc to sort:


```bash
wc -l *.pdb | sort -n
```

           9 methane.pdb
          12 ethane.pdb
          15 propane.pdb
          20 cubane.pdb
          21 pentane.pdb
          30 octane.pdb
         107 total


And now we send the output to this pipe, through another pipe, to head, so that the full pipeline becomes:


```bash
wc -l *.pdb | sort -n | head -1
```

           9 methane.pdb


** read explanation and review if necessary. use diagram from SWC lesson. 

Here’s what actually happens behind the scenes when we create a pipe. 

When a computer runs a program — any program — it creates a process in memory to hold the program’s software and its current state. 

Every process has an input channel called standard input. 

Every process also has a default output channel called standard output (or “stdout”).

The shell is actually just another program. 

whatever we type on the keyboard is sent to the shell on its standard input, and whatever it produces on standard output is displayed on our screen. 

When we tell the shell to run a program, it creates a new process and temporarily sends whatever we type on our keyboard to that process’s standard input, and whatever the process sends to standard output to the screen.

Here’s what happens when we run wc -l \*.pdb > lengths.txt. The shell starts by telling the computer to create a new process to run the wc program. Since we’ve provided some filenames as parameters, wc reads from them instead of from standard input. And since we’ve used > to redirect output to a file, the shell connects the process’s standard output to that file.

If we run wc -l \*.pdb | sort -n instead, the shell creates two processes (one for each process in the pipe) so that wc and sort run simultaneously. 

The standard output of wc is fed directly to the standard input of sort; since there’s no redirection with >, sort’s output goes to the screen. 

And if we run wc -l \*.pdb | sort -n | head -n 1, we get three processes with data flowing from the files, through wc to sort, and from sort through head to the screen.


Remember **wc** and **sort** are **filters**.

## Challenge 3: Sort -n - Pipe reading comprehension 

#### Nelle’s Pipline:  Checking Files 

Now, if we want help our researcher Nelle to check the sample files in the north-pacific-gyre/2012-07-03 directory described earlier for odd files. we’ll start from our home directory,

check your current directory:


```bash
cd north-pacific-gyre/2012-07-03
```

    

navigate to **north-pacific-gyre/2012-07-03**


```bash
pwd
```

    /Users/rotsuji/desktop/sio-swc/data-shell/north-pacific-gyre/2012-07-03



```bash
wc -l *.txt
```

         300 NENE01729A.txt
         300 NENE01729B.txt
         300 NENE01736A.txt
         300 NENE01751A.txt
         300 NENE01751B.txt
         300 NENE01812A.txt
         300 NENE01843A.txt
         300 NENE01843B.txt
         300 NENE01971Z.txt
         300 NENE01978A.txt
         300 NENE01978B.txt
         240 NENE02018B.txt
         300 NENE02040A.txt
         300 NENE02040B.txt
         300 NENE02040Z.txt
         300 NENE02043A.txt
         300 NENE02043B.txt
        5040 total



```bash
wc -l *.txt | sort -n | head -5
```

         240 NENE02018B.txt
         300 NENE01729A.txt
         300 NENE01729B.txt
         300 NENE01736A.txt
         300 NENE01751A.txt


Whoops: one of the files is 60 lines shorter than the others. When she goes back and checks it, she sees that she did that assay at 8:00 on a Monday morning — someone was probably in using the machine on the weekend, and she forgot to reset it. Before re-running that sample, she checks to see if any files have too much data:


```bash
wc -l *.txt | sort -n | tail -5
```

         300 NENE02040B.txt
         300 NENE02040Z.txt
         300 NENE02043A.txt
         300 NENE02043B.txt
        5040 total


Those numbers look good — but what’s that ‘Z’ doing there in the third-to-last line? All of her samples should be marked ‘A’ or ‘B’; by convention, her lab uses ‘Z’ to indicate samples with missing information. To find others like it, she does this:


```bash
ls *Z.txt
```

    NENE01971Z.txt	NENE02040Z.txt


Sure enough, when she checks the log on her laptop, there’s no depth recorded for either of those samples. Since it’s too late to get the information any other way, she must exclude those two files from her analysis. 

##  Challenge 4:  Piping Commands together - end of section
