---
title: "06_find-grep"
author: "Reid Otsuji"
date: "3/4/2018"
output: html_document
---

# Lesson 6: Finding Things - Using Grep

* Use grep to select lines from text files that match simple patterns.
* Use find to find files whose names match simple patterns.
* Use the output of one command as the command-line parameters to another command.
* Explain what is meant by “text” and “binary” files, and why many common tools don’t handle the latter well.


In the same way that many of us now use “Google” as a verb meaning “to find”, Unix programmers often use the word “grep”. 

“grep” is a contraction of “global/regular expression/print”, a common sequence of operations in early Unix text editors. It is also the name of a very useful command-line program.

**grep** finds and prints lines in files that match a pattern. 

For our examples, we will use a file that contains three haikus taken from a 1998 competition in Salon magazine. 

For this set of examples, we’re going to be working in the **writing** subdirectory:


```bash
pwd
```

    /Users/rotsuji/desktop/sio-swc/data-shell/molecules



```bash
cd ..
```

    


```bash
pwd
```

    /Users/rotsuji/desktop/sio-swc/data-shell



```bash
cd writing
```

    


```bash
pwd
```

    /Users/rotsuji/desktop/sio-swc/data-shell/writing



```bash
cat haiku.txt
```

    The Tao that is seen
    Is not the true Tao, until
    You bring fresh toner.
    
    With searching comes loss
    and the presence of absence:
    "My Thesis" not found.
    
    Yesterday it worked
    Today it is not working
    Software is like that.


Let’s find lines that contain the word “not”:


```bash
grep not haiku.txt
```

    Is not the true Tao, until
    "My Thesis" not found.
    Today it is not working


The word  not is the pattern we’re searching for.

It’s pretty simple: every alphanumeric character matches against itself.

After the pattern comes the name or names of the files we’re searching in.

The output is the three lines in the file that contain the letters “not”.

Now, Let’s try a different pattern: “day”.


```bash
grep day haiku.txt
```

    Yesterday it worked
    Today it is not working


This time, two lines that include the letters “day” are outputted.

However, these letters are contained within larger words. “Yesterday” and “today”

To **restrict matches to lines containing the word “day”** on its own, we can give **grep** with the **-w flag**. 

This will limit matches to word boundaries.



```bash
grep -w day haiku.txt
```

    

In this case, **there aren’t any, so grep’s output is empty.** 

Sometimes we don’t want to search for a single word, but a phrase. 

This is also easy to do with grep by **putting the phrase in quotes.**



```bash
grep -w "is not" haiku.txt
```

    Today it is not working


We’ve now seen that you don’t have to have quotes around single words, but it is useful to use quotes when searching for multiple words. 

It also helps to make it easier to distinguish between the search term or phrase and the file being searched. 

For the next remaining examples we will use quotes.

Another useful option is **-n**, which **numbers the lines** that match:



```bash
grep -n "it" haiku.txt
```

    5:With searching comes loss
    9:Yesterday it worked
    10:Today it is not working


can run **clear** command to clear the terminal, and using **“history”** will return the last commands if necessary

Here, we can see that lines 5, 9, and 10 contain the letters “it”.

We can combine options (i.e. flags) as we do with other Unix commands. 

For example, let’s find the lines that contain the word “the”. 

We can combine the option **-w (limited word bourndaries)** to find the lines that contain the word “the” and **-n** to number the lines that match:



```bash
grep -n -w "the" haiku.txt
```

    2:Is not the true Tao, until
    6:and the presence of absence:


Now we want to use the option **-i** to make our search **case-insensitive:



```bash
grep -n -w -i "the" haiku.txt
```

    1:The Tao that is seen
    2:Is not the true Tao, until
    6:and the presence of absence:


Now, we want to use the option **-v** to **invert our search**, i.e., we want to output the lines that do not contain the word “the”.


```bash
grep -n -w -v "the" haiku.txt
```

    1:The Tao that is seen
    3:You bring fresh toner.
    4:
    5:With searching comes loss
    7:"My Thesis" not found.
    8:
    9:Yesterday it worked
    10:Today it is not working
    11:Software is like that.


**grep** has lots of other options. 

To find out what they are, we can type **man grep**. 

**man** is the Unix “manual” command: it prints a description of a command and its options, and (if you’re lucky) provides a few examples of how to use it.

To navigate through the **man** pages, you may use the up and down arrow keys to move line-by-line, or try the “b” and spacebar keys to skip up and down by full page. 

Quit the man pages by typing **“q”.**

```bash
$ man grep
```

or 

```bash
$ grep --help
```

##### Mention Wildcards:

grep‘s real power doesn’t come from its options, though; it comes from the fact that patterns can include wildcards. (The technical name for these is **regular expressions**, which is what the “re” in “grep” stands for.) 



```bash
grep -E '^.o' haiku.txt
```

    You bring fresh toner.
    Today it is not working
    Software is like that.


We use the -E flag and put the pattern in quotes to prevent the shell from trying to interpret it. (If the pattern contained a \*, for example, the shell would try to expand it before running grep.) The ^ in the pattern anchors the match to the start of the line. The . matches a single character (just like ? in the shell), while the 'o' matches an actual ‘o’.

While grep finds lines in files, the find command finds files themselves. 


Again, it has a lot of options; to show how the simplest ones work, we’ll use the directory tree shown below.


Link to directory structure image: 
http://swcarpentry.github.io/shell-novice/fig/find-file-tree.svg

Nelle’s writing directory contains one file called **haiku.txt** and four subdirectories: **thesis** (which contains a sadly empty file, **empty-draft.md**), **data** (which contains two files **one.txt** and **two.txt**), a tools directory that contains the programs **format** and **stats**, and a subdirectory called **old**, with a file **oldtool**.

For our first command, let’s run **find . **


```bash
find .
```

    .
    ./.DS_Store
    ./data
    ./data/one.txt
    ./data/two.txt
    ./haiku.txt
    ./old
    ./old/.gitkeep
    ./thesis
    ./thesis/empty-draft.md
    ./tools
    ./tools/format
    ./tools/old
    ./tools/old/oldtool
    ./tools/stats


next, let’s run **find . -type d **


```bash
find . -type d
```

    .
    ./data
    ./old
    ./thesis
    ./tools
    ./tools/old


As always, the . on its own means the current working directory, which is where we want our search to start; **-type d** means **“things that are directories”**. Sure enough,find’s output is the names of the five directories in our little tree (including .):


If we change **-type d** to **-type f**, we get a **listing of all the files** instead:


```bash
find . -type f
```

    ./.DS_Store
    ./data/one.txt
    ./data/two.txt
    ./haiku.txt
    ./old/.gitkeep
    ./thesis/empty-draft.md
    ./tools/format
    ./tools/old/oldtool
    ./tools/stats


find automatically goes into subdirectories, their subdirectories, and so on to find everything that matches the pattern we’ve given it. 

Now let's try matching by name:


```bash
find . -name *.txt
```

    ./haiku.txt


We expected it to find all the text files, but it only prints out ./haiku.txt. The problem is that the shell expands wildcard characters like \* before commands run. 

Since \*.txt in the current directory expands to haiku.txt, the command we actually ran was:


```bash
find . -name haiku.txt
```

    ./haiku.txt


find did what we asked; we just asked for the wrong thing.

To get what we want, let’s do what we did with **grep: put *.txt in single quotes** to prevent the shell from expanding the \* wildcard. This way, find actually gets the pattern \*.txt, not the expanded filename haiku.txt:




```bash
find . -name '*.txt'
```

    ./data/one.txt
    ./data/two.txt
    ./haiku.txt


As we said earlier, the command line’s power lies in combining tools.

We’ve seen how to do that with pipes; let’s look at another technique. 

As we just saw, **find . -name '*.txt'** gives us a list of all text files in or below the current directory. 

How can we combine that with **wc -l** to count the lines in all those files?

The simplest way is to put the find command inside **$()**:




```bash
wc -l $(find . -name '*.txt')
```

          70 ./data/one.txt
         300 ./data/two.txt
          11 ./haiku.txt
         381 total


When the shell executes this command, the first thing it does is run whatever is inside the $(). 

It then replaces the $() expression with that command’s output. 

Since the output of find is the three filenames ./data/one.txt, ./data/two.txt, and ./haiku.txt, the **shell constructs the command**:


```bash
wc -l ./data/one.txt ./data/two.txt ./haiku.txt
```

          70 ./data/one.txt
         300 ./data/two.txt
          11 ./haiku.txt
         381 total


which is what we wanted. 

This expansion is exactly what the shell does when it expands wildcards like \* and ?, but lets us use any command we want as our own “wildcard”.

It’s very common to use find and grep together. 

The first finds files that match a pattern; the second looks for lines inside those files that match another pattern. Here, for example, we can find PDB files that contain iron atoms by looking for the string “FE” in all the .pdb files above the current directory:



```bash
grep "FE" $(find .. -name '*.pdb')
```

    ../data/pdb/heme.pdb:ATOM     25 FE           1      -0.924   0.535  -0.518


##### Binary Files Tips

We have focused exclusively on finding things in text files. What if your data is stored as images, in databases, or in some other format? One option would be to extend tools like grep to handle those formats. This hasn’t happened, and probably won’t, because there are too many formats to support.

The second option is to convert the data to text, or extract the text-ish bits from the data. This is probably the most common approach, since it only requires people to build one tool per data format (to extract information). On the one hand, it makes simple things easy to do. On the negative side, complex things are usually impossible. For example, it’s easy enough to write a program that will extract X and Y dimensions from image files for grep to play with, but how would you write something to find values in a spreadsheet whose cells contained formulas?

The third choice is to recognize that the shell and text processing have their limits, and to use a programming language such as Python instead. When the time comes to do this, don’t be too hard on the shell: many modern programming languages, Python included, have borrowed a lot of ideas from it, and imitation is also the sincerest form of praise.

#### Unix Shelll Lessons Closing:
The Unix shell is older than most of the people who use it. 

It has survived so long because it is one of the most productive programming environments ever created — maybe even the most productive.

Its syntax may be cryptic, but people who have mastered it can experiment with different commands interactively, then use what they have learned to automate their work. 

Graphical user interfaces may be better at the first, but the shell is still unbeaten at the second. 


And as Alfred North Whitehead wrote in 1911, “Civilization advances by extending the number of important operations which we can perform without thinking about them.”

